service: my-serverless-project

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements: 
    - Effect : Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:880993530241:table/MovieTable

functions:
  health:
    handler: dist/health.handler
    events:
      - http:
          path: health
          method: get
          
  createMovie:
    handler: dist/features/movie/functions/createMovie.handler
    events:
      - http:
          path: movie
          method: post 

  getMovie:
    handler: dist/features/movie/functions/getMovie.handler
    events:
      - http:
          path: movie/{id}
          method: get 

  getMovies:
    handler: dist/features/movie/functions/getMovies.handler
    events:
      - http:
          path: movie
          method: get 

  updateMovie:
    handler: dist/features/movie/functions/updateMovie.handler
    events:
      - http:
          path: movie/{id}
          method: put 

  deleteMovie:
    handler: dist/features/movie/functions/deleteMovie.handler
    events:
      - http:
          path: movie/{id}
          method: delete


  swapiGetCharacters:
    handler: dist/features/swapi/functions/getCharacter.handler
    events:
      - http:
          path: character/{id}
          method: get

  swapiGetCharacter:
    handler: dist/features/swapi/functions/getCharacters.handler
    events:
      - http:
          path: character
          method: get

  swapiGetStarchipsByCharacter:
    handler: dist/features/swapi/functions/getStarshipsByCharacter.handler
    events:
      - http:
          path: starshipByCharacter/{id}
          method: get

  swapiToSpanish:
    handler: dist/features/swapi/functions/swapiToSpanish.handler
    events:
      - http:
          path: swapiToSpanish
          method: get




resources:
  Resources:
    MovieTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: MovieTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName : id
              AttributeType : S
          KeySchema:
            - AttributeName: id
              KeyType: HASH