service: my-serverless-project

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements: 
    - Effect : Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:880993530241:table/MovieTable

functions:
  health:
    handler: dist/health.handler
    events:
      - http:
          path: health
          method: get
          
  createMovie:
    handler: dist/features/movie/functions/create.handler
    events:
      - http:
          path: createMovie
          method: post  
          
  swampiToSpanish:
    handler: dist/features/swapi/functions/swapiToSpanish.handler
    events:
      - http:
          path: swapiToSpanish
          method: get




resources:
  Resources:
    MovieTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: MovieTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName : id
              AttributeType : S
          KeySchema:
            - AttributeName: id
              KeyType: HASH