service: my-serverless-project

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements: 
    - Effect : Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:880993530241:table/MovieTable

functions:
  health:
    handler: dist/health/health.handler
    events:
      - http:
          path: health
          method: get
          
  swampiToSpanish:
    handler: dist/swampiToSpanish/swampiToSpanish.handler
    events:
      - http:
          path: swampiToSpanish
          method: get

  addMovie:
    handler: dist/addMovie/addMovie.handler
    events:
      - http:
          path: addMovie
          method: post


resources:
  Resources:
    MovieTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: MovieTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName : id
              AttributeType : S
          KeySchema:
            - AttributeName: id
              KeyType: HASH