service: my-serverless-project

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  health:
    handler: dist/health/health.handler
    events:
      - http:
          path: health
          method: get
          
  swampiToSpanish:
    handler: dist/swampiToSpanish/swampiToSpanish.handler
    events:
      - http:
          path: swampiToSpanish
          method: get
