// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "my-serverless-project",
    "version": "1"
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "health",
        "description": "",
        "operationId": "health.get.health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/movie": {
      "post": {
        "summary": "createMovie",
        "description": "",
        "tags": [
          "Movie"
        ],
        "operationId": "createMovie.post.movie",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateMovie"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Movie created successfully"
          }
        }
      },
      "get": {
        "summary": "getMovies",
        "description": "",
        "tags": [
          "Movie"
        ],
        "operationId": "getMovies.get.movie",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Movies listed successfully"
          }
        }
      }
    },
    "/movie/{id}": {
      "get": {
        "summary": "getMovie",
        "description": "",
        "tags": [
          "Movie"
        ],
        "operationId": "getMovie.get.movie/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Movie listed successfully"
          }
        }
      },
      "put": {
        "summary": "updateMovie",
        "description": "",
        "tags": [
          "Movie"
        ],
        "operationId": "updateMovie.put.movie/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateMovie"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Movie updated successfully"
          }
        }
      },
      "delete": {
        "summary": "deleteMovie",
        "description": "",
        "tags": [
          "Movie"
        ],
        "operationId": "deleteMovie.delete.movie/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Movie deleted successfully"
          }
        }
      }
    },
    "/character/{id}": {
      "get": {
        "summary": "swapiGetCharacters",
        "description": "",
        "tags": [
          "Swapi"
        ],
        "operationId": "swapiGetCharacters.get.character/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Get star wars's characters"
          }
        }
      }
    },
    "/character": {
      "get": {
        "summary": "swapiGetCharacter",
        "description": "",
        "tags": [
          "Swapi"
        ],
        "operationId": "swapiGetCharacter.get.character",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Get star wars's character"
          }
        }
      }
    },
    "/starshipByCharacter/{id}": {
      "get": {
        "summary": "swapiGetStarchipsByCharacter",
        "description": "",
        "tags": [
          "Swapi"
        ],
        "operationId": "swapiGetStarchipsByCharacter.get.starshipByCharacter/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Get star wars's starchip by character"
          }
        }
      }
    }
  },
  "definitions": {
    "Movie": {
      "properties": {
        "id": {
          "title": "Movie.id",
          "type": "string"
        },
        "title": {
          "title": "Movie.title",
          "type": "string"
        },
        "releaseYear": {
          "title": "Movie.releaseYear",
          "type": "number"
        },
        "director": {
          "title": "Movie.director",
          "type": "string"
        },
        "genre": {
          "title": "Movie.genre",
          "type": "string"
        },
        "durationMinutes": {
          "title": "Movie.durationMinutes",
          "type": "number"
        },
        "rating": {
          "title": "Movie.rating",
          "type": "number"
        },
        "description": {
          "title": "Movie.description",
          "type": "string"
        },
        "done": {
          "title": "Movie.done",
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "title",
        "releaseYear",
        "director",
        "genre",
        "durationMinutes",
        "rating",
        "done"
      ],
      "additionalProperties": false,
      "title": "Movie",
      "type": "object"
    },
    "CreateMovie": {
      "properties": {
        "title": {
          "title": "CreateMovie.title",
          "type": "string"
        },
        "releaseYear": {
          "title": "CreateMovie.releaseYear",
          "type": "number"
        },
        "director": {
          "title": "CreateMovie.director",
          "type": "string"
        },
        "genre": {
          "title": "CreateMovie.genre",
          "type": "string"
        },
        "durationMinutes": {
          "title": "CreateMovie.durationMinutes",
          "type": "number"
        },
        "rating": {
          "title": "CreateMovie.rating",
          "type": "number"
        },
        "description": {
          "title": "CreateMovie.description",
          "type": "string"
        }
      },
      "required": [
        "title",
        "releaseYear",
        "director",
        "genre",
        "durationMinutes",
        "rating",
        "description"
      ],
      "additionalProperties": false,
      "title": "CreateMovie",
      "type": "object"
    },
    "UpdateMovie": {
      "properties": {
        "title": {
          "title": "UpdateMovie.title",
          "type": "string"
        },
        "rating": {
          "title": "UpdateMovie.rating",
          "type": "number"
        },
        "description": {
          "title": "UpdateMovie.description",
          "type": "string"
        },
        "done": {
          "title": "UpdateMovie.done",
          "type": "boolean"
        }
      },
      "required": [
        "title",
        "rating",
        "description",
        "done"
      ],
      "additionalProperties": false,
      "title": "UpdateMovie",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "host": "894e2q7rij.execute-api.us-east-1.amazonaws.com",
  "schemes": [
    "https",
    "http"
  ]
};